# 应用名称
spring:
  application:
    name: demo
# 应用服务 WEB 访问端口
server:
  port: 8080
sftp-pool:
  lifo: false
  pool-config:
    lifo: false
  minIdlePerKey: 1
  maxIdlePerKey: 8
  maxTotalPerKey: 8
  softMinEvictableIdleTimeMillis: 30000
  timeBetweenEvictionRunsMillis: 10000
  connConfigs:
    sftp1:
      host: 127.0.0.1
      port: 22
      userName: test
      password: test
    sftp2:
      host: 192.168.1.1
      port: 22
      userName: test
      password: test
